class SessionPalletDetail {
  final int palletId;

  /// The pallet number: 3-digit product-type prefix + 9-digit serial
  /// (`037000000051`), generated by the backend. The same value is printed and
  /// encoded on the label and is what reprint-by-number looks up.
  final String scannedValue;

  /// [scannedValue] without its prefix (`000000051`). Not a pallet number on
  /// its own — two products can share it.
  final String serialNumber;
  final int quantity;
  final String sourceType;
  final DateTime createdAt;
  final String createdAtDisplay;

  /// Grinding label marker, decided by the backend from the pallet's grinding
  /// order. All three are absent on an older backend, which means "no marker,
  /// reprint allowed".
  final bool? grindingRecommended;
  final String? grindingLabelText;
  final bool? labelReprintAllowed;

  /// The pallet's grinding order status (e.g. `PENDING_APPROVAL`) and its
  /// Arabic label. Absent when the pallet has no grinding order.
  final String? grindingStatus;
  final String? grindingStatusLabel;

  const SessionPalletDetail({
    required this.palletId,
    required this.scannedValue,
    required this.serialNumber,
    required this.quantity,
    required this.sourceType,
    required this.createdAt,
    required this.createdAtDisplay,
    this.grindingRecommended,
    this.grindingLabelText,
    this.labelReprintAllowed,
    this.grindingStatus,
    this.grindingStatusLabel,
  });

  /// `false` only when the backend says so (grinding started or finished).
  bool get isLabelReprintAllowed => labelReprintAllowed ?? true;

  /// The full pallet number to show. Falls back to [serialNumber] only if a
  /// response ever omits [scannedValue]; the prefix is never rebuilt here.
  String get palletNumber {
    final full = scannedValue.trim();
    return full.isNotEmpty ? full : serialNumber.trim();
  }
}

class SessionProductTypeGroup {
  final int productTypeId;
  final String productTypeName;
  final String productTypePrefix;
  final int completedPalletCount;
  final List<SessionPalletDetail> pallets;

  const SessionProductTypeGroup({
    required this.productTypeId,
    required this.productTypeName,
    required this.productTypePrefix,
    required this.completedPalletCount,
    required this.pallets,
  });
}

class SessionProductionDetail {
  final int lineId;
  final int authorizationId;
  final List<SessionProductTypeGroup> groups;

  const SessionProductionDetail({
    required this.lineId,
    required this.authorizationId,
    required this.groups,
  });
}
